sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- echo "This design module has no tests"
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: UOB2gryGIq91LmvwIqVpHX2GQgSc1EZ+PGGgR3lzluLAbcOWqgtSQW0OOwLUuY0EwOedFzVXKvuagCLHMcd/jpXsTq9y7kr5FXOs2bCCXar22eG1eCiynf5GP9BejDpTfD/KbWxthB9W0MPI/w/4imcLmzyO95SgR8x5NcmEPokYLYKSDtk9Z+B8hAA0YiEYcR1VZyKfHGLiGtl+6RGqKOZ3J5ZoWsRLl4yEo3ePb0ZqJS6csnmmGIqRO9pk1jW53EapC5XOlAvEtmYRgkJWlOoPNGwi9zgwANu8Hay/J44poISPtF9Puht+e9qPpF9D698QP8zPquBh32QFgdfzt66AagMfDS+pmkeDUVCF4Al/YEVRD89+bKGbcds7K3cU3fOnQzAi6ma6LJ+UQTOxJyujiW1/eiazpQArV2HglDqGYRrlji1Ph/HY7fUAyhAM/uWaMoP3NfGK2mTZByYmVTIGZlDyBaY/4MhhUOX7TXUu295cmvbRbCQgyLtNHZofkwQXPvlO9i8oa1o5VWgHKJ5+EeNnk+MZjRhoLpmcbmHd0aoaJQOYJDdpxYStHNrIgPSIyMPu2pfsXhdpNHWFO4xKko4hWiwqj6fyd2F7G7mKl5WHAVJuE0VSrVN/VRbbP5jtqSdYSA56wJOCzb6XKeNLJgLWxxB9xQN4r2GDCKo=
  - secure: oA3dONVv2jbQHwM57q8NBRAIxFjv5GR3w5EI+RQOFHnZ697cXVBLPWlLuXOQTf0pm1inbTJ/ynKyOnB9LNRpzLzQjMfhcNu3Sgs0uygx8oWVj+cjxloIJWD5tbv6w0MMbwKh21wNGfzETbMGmqUQh9CvUpgOYOc1ljHLyUk6MdQEemZeO4NyMxy585uryETdZDk7xsHRFpdoC5ydmu2x7wEWkj706vjwyH0JI3JzlisVxVTV6sBLhhjls+xTeO8RoqqTw8D1ISh3fUmCYPwuV68Fo2swW66j25NDnLIUHsFfu8bidLIGLOnRTRSwezBitu1qcraGMV096AJ1d7B6mxRIUPtHbucWq60GU5Zc/f2iQdk+k+sVaeREnDqpUW8RyBUlqwbuYQcsvkSZrGOGpYRZL+G7EjgLO1EGpH1it7c25WJxDRYuAk7XAd+/saPHwHtiEt0zejkTu2rgedHAuhrnZoZA3zn83v6GuYClrgS/7bn2p8f7sLMab8IjBSyHBE0bLpZ+VKeV0gzJlfVM80GrW7tLGm4XqCGf6umGVi5E7ebQs34LffY3fBbceUHurkk/FHTLjcrwFUIyBvD0sACRafxCJc6Gw9yye6eWYsJcWn8FRQz/5MIpVmPQ12JXi3fFHuCNj8W/W/sMvoP7oUhTqG66gBagC86UmN2r+Sg=
